Building DAG of jobs...
Provided cores: 32
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	create_results
	1

rule create_results:
    input: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2973.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/242.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3010.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/1905a.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/241.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2306.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/224.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/239.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3062.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/222.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/40.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/50.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/51.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/42.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/48.tsv
    jobid: 0

Error in rule create_results:
    jobid: 0
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2973.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/242.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3010.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/1905a.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/241.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2306.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/224.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/239.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3062.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/222.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/40.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/50.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/51.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/42.tsv, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/48.tsv

RuleException:
CalledProcessError in line 379 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakeprova.py:
Command ' set -euo pipefail;  ls > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2973.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/242.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3010.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/1905a.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/241.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2306.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/224.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/239.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/3062.tsv /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/222.tsv ' returned non-zero exit status 2.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakeprova.py", line 379, in __rule_create_results
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job create_results since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/provina1/2973.tsv
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2018-01-04T151506.055152.snakemake.log
